@baseUrl = http://localhost:3001
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNTkzNzA5MTg4LCJleHAiOjE1OTM3MTIxODh9.BEFtmN9kWMW1Z-a2tACW3LCY0YQIJV1mOaI_apGbSpM

### Create a Account
POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "email": "dbz7@gmail.com",
    "password": "123456",
    "password_confirmation": "123456"
}

### Sign in
POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
    "email": "dbz@gmail.com",
    "password": "123456"
}


### List Links
GET {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Create Link
POST {{baseUrl}}/link
Content-Type: {{contentType}}

{
        "label": "Facebook",
        "url": "https://facebook.com",
        "isSocial": false
}

### Get a link by Id
GET {{baseUrl}}/link/1
Content-Type: {{contentType}}

### Edit Link
PUT {{baseUrl}}/link/1
Content-Type: {{contentType}}

{
    "label": "Melhor motor de busca",
    "url": "https://facebook.com",
    "isSocial": true
}

### Delete a link

DELETE {{baseUrl}}/link/3
Content-Type: {{contentType}}